Repository opentelekomcloud/ansible-collection-cloud, pull requests merged in 2020-10, with the labels that each got.

#34 NAT modules snat, dnat, gateway
  meta/runtime.yml
  plugins/modules/nat_dnat_rule.py
  plugins/modules/nat_gateway.py
  plugins/modules/nat_snat_rule.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#33 lb_member and lb_healthmonitor modules
  meta/runtime.yml
  plugins/modules/lb_healthmonitor.py
  plugins/modules/lb_healthmonitor_info.py
  plugins/modules/lb_member.py
  plugins/modules/lb_member_info.py
  tests/integration/targets/lb_healtmonitor_info/tasks/main.yaml
  tests/integration/targets/loadbalancer/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#47 floating_ip module forked and changed to allocate fips without server
  meta/runtime.yml
  plugins/modules/floating_ip.py
  tests/integration/targets/floating_ip/tasks/main.yaml
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#49 NAT functional tests and minor fixes
  plugins/modules/nat_dnat_rule.py
  plugins/modules/nat_gateway.py
  plugins/modules/nat_snat_rule.py
  tests/integration/targets/nat/tasks/main.yaml
Labels: gate

#57 NAT: add ignore_errors to integration test
  tests/integration/targets/nat/tasks/main.yaml
Labels: enhancement, gate

#54 Change README and add module descriptions
  README.md
Labels: documentation, gate

#58 Fix eip alloc
  plugins/modules/loadbalancer.py
  tests/integration/targets/loadbalancer/tasks/main.yaml
Labels: gate
