Repository opentelekomcloud/ansible-collection-cloud, pull requests merged in 2020-09, with the labels that each got.

#18 Waf certificate
  meta/runtime.yml
  plugins/modules/waf_certificate.py
  plugins/modules/waf_certificate_info.py
  test-requirements.txt
  tests/integration/targets/waf_certificate/tasks/main.yaml
  tests/integration/targets/waf_certificate_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#17 Snapshot info
  meta/runtime.yml
  plugins/modules/volume_snapshot_info.py
  tests/integration/targets/volume_snapshot_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#19 Waf domain
  meta/runtime.yml
  plugins/modules/waf_domain.py
  plugins/modules/waf_domain_info.py
  tests/integration/targets/waf_certificate/tasks/main.yaml
  tests/integration/targets/waf_domain/tasks/main.yaml
  tests/integration/targets/waf_domain_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#23 fix wrong list for waf_cert
  plugins/modules/waf_certificate_info.py
  tests/integration/targets/waf_certificate/tasks/main.yaml
Labels: bug, gate

#25 Rds backup info
  meta/runtime.yml
  plugins/modules/rds_backup_info.py
  tests/integration/targets/rds_backup_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#27 vpc peering info module
  meta/runtime.yml
  plugins/modules/vpc_peering_info.py
  tests/integration/targets/vpc_peering_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#26 Corrected backup info module
  meta/runtime.yml
  plugins/modules/volume_backup_info.py
  tests/integration/targets/volume_backup_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#22 NAT info modules gateway, snat, dnat
  meta/runtime.yml
  plugins/modules/nat_dnat_rule_info.py
  plugins/modules/nat_gateway_info.py
  plugins/modules/nat_snat_rule_info.py
  plugins/modules/rds_flavor_info.py
  tests/integration/targets/nat_dnat_rule_info/tasks/main.yaml
  tests/integration/targets/nat_gateway_info/tasks/main.yaml
  tests/integration/targets/nat_snat_rule_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#24 Loadbalancer listener module
  meta/runtime.yml
  plugins/modules/lb_listener.py
  plugins/modules/lb_listener_info.py
  plugins/modules/loadbalancer.py
  plugins/modules/loadbalancer_info.py
  tests/integration/targets/loadbalancer/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#28 Waf cert create from file
  plugins/modules/waf_certificate.py
Labels: enhancement, gate

#31 nail down importlib-metadata version
  test-requirements.txt
Labels: gate

#32 Correct vpc peering info module
  plugins/modules/vpc_peering_info.py
Labels: gate

#29 Loadbalancer pool module (backend server group)
  meta/runtime.yml
  plugins/modules/lb_listener.py
  plugins/modules/lb_pool.py
  plugins/modules/lb_pool_info.py
  tests/integration/targets/loadbalancer/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate
