Repository opentelekomcloud/ansible-collection-cloud, pull requests merged in 2020-11, with the labels that each got.

#53 security_group_info module added which is missing in openstack.cloud.* collection
  meta/runtime.yml
  plugins/modules/security_group_info.py
  tests/integration/targets/security_group_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#62 Hotfix NAT integration test
  tests/integration/targets/nat/tasks/main.yaml
Labels: gate

#39 Dedicated Host modules
  meta/runtime.yml
  plugins/modules/deh_host.py
  plugins/modules/deh_host_info.py
  plugins/modules/deh_host_type_info.py
  plugins/modules/deh_server_info.py
  tests/integration/targets/deh_host/tasks/main.yaml
  tests/integration/targets/deh_host_info/tasks/main.yaml
  tests/integration/targets/deh_host_type_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#61 ELB certificate
  meta/runtime.yml
  plugins/modules/lb_certificate.py
  plugins/modules/lb_certificate_info.py
  plugins/modules/lb_member.py
  test-requirements.txt
  tests/integration/targets/lb_certificate/tasks/main.yaml
  tests/integration/targets/lb_certificate_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#60 document missing parameters for lb_listener_info
  plugins/modules/lb_listener_info.py
Labels: gate

#42 Vpc route info
  meta/runtime.yml
  plugins/modules/vpc_route_info.py
  tests/integration/targets/vpc_route_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#67 ELB: Fix errors on rerun
  plugins/modules/lb_certificate.py
  plugins/modules/lb_healthmonitor.py
  plugins/modules/lb_listener.py
  plugins/modules/lb_member.py
  plugins/modules/lb_pool.py
  plugins/modules/loadbalancer.py
  tests/integration/targets/lb_certificate/tasks/main.yaml
  tests/integration/targets/loadbalancer/tasks/main.yaml
Labels: bug, gate

#55 Rds backup
  meta/runtime.yml
  plugins/modules/rds_backup.py
  tests/integration/targets/rds_backup/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#59 AS config
  meta/runtime.yml
  plugins/modules/as_config.py
  tests/integration/targets/as_config/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#72 Anti ddos info
  meta/runtime.yml
  plugins/modules/anti_ddos_fip_statuses_info.py
  tests/integration/targets/anti_ddos_fip_statuses_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#56 As group
  meta/runtime.yml
  plugins/modules/as_group.py
  tests/integration/targets/as_group/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#30 Vpc peering
  meta/runtime.yml
  plugins/modules/vpc_peering.py
  tests/integration/targets/vpc_peering/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#43 Vpc route module
  meta/runtime.yml
  plugins/modules/vpc_route.py
  tests/integration/targets/vpc_route/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#64 DNS Modules
  plugins/modules/dns_floating_ip.py
  plugins/modules/dns_recordset.py
  plugins/modules/dns_zones.py
  tests/integration/targets/dns/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#73 Add new test, fix logic and small issues
  plugins/modules/rds_backup_info.py
  tests/integration/targets/rds_backup_info/tasks/main.yaml
Labels: gate
