Repository opentelekomcloud/ansible-collection-cloud, pull requests merged in 2021-06, with the labels that each got.

#117 Do not pass as.group.delete_volume unless true
  plugins/modules/as_group.py
Labels: gate

#113 Allow not waiting for RDS
  plugins/modules/rds_instance.py
Labels: gate

#100 DMS Modules
  plugins/modules/dms_instance.py
  plugins/modules/dms_instance_info.py
  plugins/modules/dms_instance_topic.py
  plugins/modules/dms_instance_topic_info.py
  plugins/modules/dms_message.py
  plugins/modules/dms_queue.py
  plugins/modules/dms_queue_group.py
  plugins/modules/dms_queue_group_info.py
  plugins/modules/dms_queue_info.py
  tests/integration/targets/dms/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#115 cce fixes for network and data vols
  plugins/modules/cce_cluster_node.py
  plugins/modules/cce_node_pool.py
  tests/integration/targets/cce_cluster_node/aliases
  tests/integration/targets/cce_cluster_node/tasks/main.yaml
  tests/integration/targets/cce_lifecycle/tasks/main.yaml
Labels: bug, gate

#118 Add role metadata
  roles/vpc_peering/README.rst
  roles/vpc_peering/meta/main.yml
Labels: gate

#119 move rst to md in role readme
  roles/vpc_peering/README.md
  roles/vpc_peering/tasks/destroy.yaml
Labels: gate

#116 Tox Script + Sphinx for ansible documentation
  .gitignore
  doc/requirements.txt
  doc/source/antiddos.rst
  doc/source/as.rst
  doc/source/cce.rst
  doc/source/ces.rst
  doc/source/conf.py
  doc/source/deh.rst
  doc/source/dns.rst
  doc/source/ecs.rst
  doc/source/elb.rst
  doc/source/index.rst
  doc/source/misc.rst
  doc/source/nat.rst
  doc/source/rds.rst
  doc/source/volume.rst
  doc/source/vpc.rst
  doc/source/vpc_peering.rst
  doc/source/waf.rst
  docs/guidelines.rst
  galaxy.yml
  plugins/modules/dns_zones.py
  test-requirements.txt
  tests/integration/targets/dns/tasks/main.yaml
  tox.ini
Labels: gate
