Repository opentelekomcloud/ansible-collection-cloud, pull requests merged in 2022-08, with the labels that each got.

#198 Modules examples
  doc/examples/10_relation_database.yaml
  doc/examples/1_initial_infra.yaml
  doc/examples/2_volume_backup_and_maintenance.yaml
  doc/examples/3_autoscaling.yaml
  doc/examples/4_as_policy.yaml
  doc/examples/5_cce_cluster.yaml
  doc/examples/6_loadbalancer.yaml
  doc/examples/7_loadbalancer_info.yaml
  doc/examples/8_monitoring.yaml
  doc/examples/9_cloud_search.yaml
Labels: documentation, gate

#217 kms info module
  doc/examples/10_relation_database.yaml
  doc/examples/1_initial_infra.yaml
  doc/examples/2_volume_backup_and_maintenance.yaml
  doc/examples/3_autoscaling.yaml
  doc/examples/5_cce_cluster.yaml
  doc/examples/6_loadbalancer.yaml
  doc/examples/8_monitoring.yaml
  doc/examples/9_cloud_search.yaml
  meta/runtime.yml
  plugins/modules/kms_info.py
  tests/integration/targets/kms_info/tasks/main.yaml
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, gate

#218 [CSS] cluster create backup strategy fix
  plugins/modules/css_cluster.py
  tests/integration/targets/dms/aliases
Labels: gate

#222 Usecases examples
  README.md
  examples/10_relation_database.yaml
  examples/11_document_database.yaml
  examples/12_dedicated_host.yaml
  examples/1_initial_infra.yaml
  examples/2_volume_backup_and_maintenance.yaml
  examples/3_autoscaling.yaml
  examples/4_as_policy.yaml
  examples/5_cce_cluster.yaml
  examples/6_loadbalancer.yaml
  examples/7_loadbalancer_info.yaml
  examples/8_monitoring.yaml
  examples/9_cloud_search.yaml
Labels: gate
